import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Metadata properties that are compatible with social media shares
  openGraph: {
    // Creates a preview of shares
    title: "Create Next App",
    description: "Generated by create next app",
    type: "website",
    url: "http://localhost:3000",
    // Image used for the preview
    images: ["imageUrl"],
    // Make sure the image is stored in the public folder!
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
